sudo : true
language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.0.0-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
# command to install dependencies
install:
  - "conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy"
  - "conda install --yes pytest-cov"
  - "conda install --yes  pytest-pep8"
  - "conda install --yes primesieve"
  - "pip install coveralls"
  - "pip install ."
# command to run tests
script:
  - py.test --pep8 --cov=euler --cov-report term-missing
after_success:
  - coveralls
