sudo : true
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.0.0-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
# command to install dependencies
install:
  - "conda install --yes python=$TRAVIS_PYTHON_VERSION numpy=1.10 scipy=0.17"
  - "pip install nose-cov"
  - "pip install tissue"
  - "pip install primesieve"
  - "pip install coveralls"
  - "pip install ."
# command to run tests
script:
  - nosetests --with-cov --with-tissue --cov=euler --cov-report term-missing
after_success:
  - coveralls
